apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: demo
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo "App is running" && sleep 3600']
    envFrom:
    - configMapRef:
        name: app-cm
