apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-05-18T04:29:22Z"
  generation: 1
  labels:
    run: nginx
    tier: frontend
    type: app1
  name: nginx
  namespace: default
  resourceVersion: "559028"
  uid: d62c8387-b533-4755-9415-512c4fabfe3e
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
  nodeName: first-cluster-worker