apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-05-11T07:08:14Z"
  generation: 1
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "320996"
  uid: 974c5833-881a-4bbd-8d16-0503b59e455e
spec:
  containers:
  - image: nginx
    name: nginx
  nodeName: first-cluster-worker